### ISSUE TITLE
www-client/firefox-76.0.1 can't apply patch because it already exists leading to getting stuck pre-compile

### ISSUE THREAD

**Issue by imatimba** [perfect7gentleman/pg_overlay#87]
First of all many thanks for this ebuild.

Build log: https://clbin.com/6m40C
Emerge --info: https://clbin.com/sHjF0

Relevant part:

>  * Applying mozilla-1625431.patch ...
> patching file dom/media/platforms/ffmpeg/FFmpegVideoDecoder.cpp
> Hunk #1 succeeded at 181 with fuzz 2 (offset 9 lines).                                                                                                                                [ ok ]
>  * +++++++++++++++++++++++++
>  * Patch mozilla-1625431.patch is APPLIED
>  * +++++++++++++++++++++++++
> Reversed (or previously applied) patch detected!  Assume -R? [n] 

If you press Enter selecting the default [n] nothing happens and the build gets stuck there.

**Comment by thubble** [comment]
This is due to the patch "mozilla-1628690.patch", it's now included in the Gentoo patchset. Removing that patch allows the build to continue.

It looks like the ebuild is attempting to check if a patch is already applied by using "patch --dry-run", but it would need to add "-f" to avoid the prompt. (Unless the prompt is intentional).

**Comment by thubble** [comment]
It looks like "mozilla-1625431.patch" is also now included in the Gentoo patchset. It applies, but then causes a build failure due to a duplicate definition.

**Comment by perfect7gentleman** [comment]
fixed.

**Comment by imatimba** [comment]
Thanks
